accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views as user_views
from stocks import views as st_view

urlpatterns = [
    path('home/', user_views.Home.as_view(), name='home'),
    path('user/', user_views.UserListView.as_view(), name='user'),
    path('roles/', user_views.RoleListView.as_view(), name='roles'),
    path('role/', user_views.RoleCreationView.as_view(), name='role'),
    path('edit_role/<int:id>/', user_views.EditRoleView.as_view(), name='edit_role'),
    path('delete_role/<int:id>/', user_views.DeleteRoleView.as_view(), name='delete_role'),
    path('signup/', user_views.SignUpView.as_view(), name='signup'),
    path('edit/<int:id>/', user_views.EditProfileView.as_view(), name='edit'),
    path('change_password/', user_views.PasswordUpdateView.as_view(), name='change_password'),
    path('deactivate/<int:id>/', user_views.DeactivateView.as_view(), name='deactivate'),
    path('activate/<int:id>/', user_views.ActivateView.as_view(), name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout_view'),
    path('setting/', user_views.Setting.as_view(), name='setting'),
    path('account_report/', user_views.AccountPDFView.as_view(), name='account_report'),
]

purchase/urls.py
from django.urls import path
from purchase import views as purchase_views

urlpatterns = [
    path('purchases/', purchase_views.PurchaseListView.as_view(), name='purchases'),
    path('purchase/', purchase_views.PurchaseCreationView.as_view(), name='purchase'),
    path('edit_purchase/<int:id>/', purchase_views.EditPurchaseView.as_view(), name='edit_purchase'),
    path('delete_purchase/<int:id>/', purchase_views.DeletePurchaseView.as_view(), name='delete_purchase'),
    path('purchase_report/', purchase_views.PurchasePDFView.as_view(), name='purchase_report')
]

sales/urls.py
from django.urls import path
from sales import views as sales_views

urlpatterns = [
    path('sales/', sales_views.SalesListView.as_view(), name='sales'),
    path('sale/', sales_views.SalesCreationView.as_view(), name='sale'),
    path('edit_sale/<int:id>/', sales_views.EditSalesView.as_view(), name='edit_sale'),
    path('delete_sale/<int:id>/', sales_views.DeleteSalesView.as_view(), name='delete_sale'),
    path('checkout/', sales_views.CheckoutView.as_view(), name='checkout'),
    path('sales_report/', sales_views.SalesPDFView.as_view(), name='sales_report'),
    path('sales_receipt/', sales_views.PrintReceiptView.as_view(), name='sales_receipt')
]

stocks/urls.py
from django.urls import path,re_path
from stocks import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='products'),
    path('product/', views.ProductCreationView.as_view(), name='product'),
    path('edit_product/<int:id>/', views.EditProductView.as_view(), name='edit_product'),
    path('delete_product/<int:id>/', views.DeleteProductView.as_view(), name='delete_product'),
    path('product_report/', views.ProductPDFView.as_view(), name='product_report')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, PermissionsMixin, Group)

class UserManager(BaseUserManager):
    
    def create_user(self,username,email,password = None):
        if username is None:
            raise ValueError('Users should have a username')
        if email is None:
            raise ValueError('Users should have an Email')
        if password is None:
            raise ValueError('Users should have a password')
        
        user = self.model(username = username,email = self.normalize_email(email))
        user.set_password(password)
        user.is_active = True
        user.save(using = self._db)
        return user
    
    def create_superuser(self,username,email,password):
        
        user = self.create_user(username,email,password = password)
        user.is_admin = True
        user.save(using = self._db)
        return user
    
class User(AbstractBaseUser,PermissionsMixin):
    
    username = models.CharField(max_length = 255, unique = True)
    email = models.EmailField(verbose_name = 'email_address',max_length = 255, unique = True)        
    is_active = models.BooleanField(default = True)
    is_admin = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    
    objects = UserManager()
    
    def __str__(self):
        return self.username
    
    def delete (self, using = None, keep_parents = False):
        self.is_active = False
        self.save()
        
    def get_full_name (self):
        return self.username
    
    def get_short_name(self):
        return self.username
    
    def has_perm(self, perm, obj = None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin
    
class Role(Group):
    description = models.TextField(max_length=100,unique=True)
    
    def __str__(self):
        return self.name

expenses/models.py
from django.db import models
from accounts.models import User

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50,unique=True)
    description = models.TextField(max_length=100,unique=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Expenses(models.Model):
    category = models.ForeignKey(ExpenseCategory, on_delete=models.DO_NOTHING)
    description = models.TextField(max_length=100,unique=True)
    amount = models.FloatField(verbose_name='amount')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description

sales/models.py
from django.db import models
from accounts.models import User
from stocks.models import Product

class Sales(models.Model):
    name = models.CharField(max_length=50)
    item = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    quantity = models.PositiveIntegerField()
    unit_price = models.FloatField(verbose_name='unit price')
    total_amount = models.PositiveIntegerField(verbose_name='total amount')
    status = models.CharField(max_length=50, default='pending')
    sold_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    sold_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

purchase/forms.py
from django import forms
from .models import Purchase

class PurchaseCreationForm(forms.ModelForm):

    class Meta:
        model = Purchase
        fields = ('name', 'description', 'quantity','cost_price', 'current_stock_level','total_stock_level', 'supplier_tel', 'created_by')

class EditPurchaseForm(forms.ModelForm):
   
    class Meta:
        model = Purchase
        fields = ['name', 'description', 'quantity', 'cost_price','current_stock_level','total_stock_level', 'supplier_tel',]
        exclude = ['created_by']

sales/forms.py
from django import forms
from sales.models import Sales

class SalesCreationForm(forms.ModelForm):
    
    class Meta:
        model = Sales
        fields = ('name','item', 'quantity', 'unit_price', 'total_amount', 'sold_by')
        
    def save(self, commit = True):
        sale = super(SalesCreationForm,self).save(commit = False)
        
        if commit:
            sale.name = self.cleaned_data.get('name')
            sale.unit_price = self.cleaned_data.get('unit_price')
            sale.total_amount = self.cleaned_data.get('total_amount')
            sale.sold_by = self.cleaned_data.get('sold_by')
            sale.save()
        return sale
        
class SalesEditForm(forms.ModelForm):
    
    class Meta:
        model = Sales
        fields = ['item', 'quantity']

stocks/forms.py
from django import forms
from .models import Product

class ProductCreationForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['name','description','quantity','unit_price','stock_level','created_by_id']
        
class EditProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['name','description','quantity','unit_price','stock_level']
        exclude = ['created_by_id']

accounts/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import (ListView, UpdateView, DetailView, DeleteView, CreateView, TemplateView )
from .forms import (UserRegisterForm, EditProfileForm,RoleCreationForm, EditRoleForm )
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.models import Group
from django.contrib import auth
from django.shortcuts import render
from company.models import Company
from .models import User, Role
from stocks.models import Product
from sales.models import Sales
from purchase.models import Purchase
from expenses.models import ExpenseCategory, Expenses
from .permissions import assign_permissions, remove_permissions
from decorators.decorators import group_required
from easy_pdf.views import PDFTemplateView
from helpers.generate_pdf import generate_report

decorators = [group_required(['Admin','Manager','General Manager'])]

@method_decorator(decorators, name='dispatch')
class UserListView(ListView):
    queryset = User.objects.all().order_by('id')
    paginate_by = 10
    context_object_name = 'user_list'
    template_name = 'accounts/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company'] = Company.objects.all().values()[0]

        return render(self.request, 'accounts/user.html', context)

@method_decorator(login_required, name='dispatch')
class EditProfileView(UpdateView, DetailView):
    template_name = 'accounts/edit.html'
    pk_url_kwarg = 'id'
    form_class = EditProfileForm
    queryset = User.objects.all()
    success_url = reverse_lazy('setting')
    old_role = []

    def get(self, request, *args, **kwargs):
        self.user = User.objects.get(id=kwargs['id'])

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['roles'] = Group.objects.all().values_list('name', flat=True)

        return context

    def post(self, request, *args, **kwargs):
        user = User.objects.get(id=kwargs['id'])
        self.old_role += user.groups.all().values_list('name', flat=True)
        new_role = request.POST.get('role', None)

        if len(self.old_role) > 0:
            user.groups.remove(Group.objects.get(name=self.old_role[0]))

        if new_role is not None:
            user.groups.add(Group.objects.get(name=new_role))

        return super().post(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class PasswordUpdateView(PasswordChangeView):
    template_name = 'accounts/change_password.html'
    pk_url_kwarg = 'id'
    form_class = PasswordChangeForm
    queryset = User.objects.all()
    success_url = reverse_lazy('setting')

@method_decorator(decorators, name='dispatch')
class DeactivateView(DeleteView):
    template_name = 'accounts/deactivate.html'
    pk_url_kwarg = 'id'
    queryset = User.objects.all()
    success_url = reverse_lazy('setting')

@method_decorator(login_required, name='dispatch')
class ActivateView(DeleteView):
    template_name = 'accounts/activate.html'
    pk_url_kwarg = 'id'
    queryset = User.objects.all()
    success_url = reverse_lazy('setting')

@method_decorator(decorators, name='dispatch')
class SignUpView(CreateView):
    form_class = UserRegisterForm
    template_name = 'accounts/signup.html'
    success_message = 'Success: Sign up succeeded.'
    success_url = reverse_lazy('setting')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['roles'] = Group.objects.all().values_list('name', flat=True)

        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save()

            role_name = request.POST['role']
            user.groups.add(Group.objects.get(name=role_name))

            return HttpResponseRedirect(self.success_url)

        return super().post(request, *args, **kwargs)

@method_decorator(decorators, name='dispatch')
class RoleCreationView(CreateView):
    form_class = RoleCreationForm
    template_name = 'accounts/add_role.html'
    success_message = 'Success: Role creation succeeded.'
    success_url = reverse_lazy('setting')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            role = form.save()

            perm = [request.POST['user_perm']]
            if 'full' in perm:
                assign_permissions(role, perm, full=True)
            else:
                assign_permissions(role, perm)

            return HttpResponseRedirect(self.success_url)

        return super().post(request, *args, **kwargs)

@method_decorator(decorators, name='dispatch')
class RoleListView(ListView):
    queryset = Role.objects.all().order_by('id')
    paginate_by = 10
    context_object_name = 'role_list'
    template_name = 'accounts/roles.html'

@method_decorator(decorators, name='dispatch')
class EditRoleView(UpdateView, DetailView):
    template_name = 'accounts/edit_role.html'
    pk_url_kwarg = 'id'
    form_class = EditRoleForm
    queryset = Role.objects.all()
    success_url = reverse_lazy('setting')
    old_perms = []

    def get(self, request, *args, **kwargs):
        self.edit_role = Role.objects.get(id=kwargs['id'])

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['role_perms'] = self.edit_role.permissions.all().values_list('codename', flat=True)

        return context

    def post(self, request, *args, **kwargs):

        edit_role = Role.objects.get(id=kwargs['id'])
        self.old_perms += edit_role.permissions.all().values_list('codename', flat=True)
        new_perm = request.POST.getlist('user_perm')

        if not new_perm:
            raise ValueError("You must assign atleast 1 permission for the new role")

        if 'full' in new_perm or len(new_perm) == 4:
            edit_role.permissions.remove()
            assign_permissions(edit_role, new_perm, full=True)
        else:
            if len(new_perm) > 1:
                for perm in new_perm:
                    if perm not in self.old_perms:
                        assign_permissions(edit_role, [perm])
                remove_permissions(edit_role, new_perm, self.old_perms)
            else:
                if new_perm not in self.old_perms:
                    assign_permissions(edit_role, new_perm)
                remove_permissions(edit_role, new_perm, self.old_perms)

        return super().post(request, *args, **kwargs)

@method_decorator(decorators, name='dispatch')
class DeleteRoleView(DeleteView):
    template_name = 'accounts/delete_role.html'
    pk_url_kwarg = 'id'
    queryset = Role.objects.all()
    success_url = reverse_lazy('setting')

@method_decorator(login_required, name='dispatch')
class Home(ListView):
    queryset = User.objects.all().order_by('id')
    paginate_by = 10
    template_name = 'accounts/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = len(User.objects.all())
        context['roles'] = len(Group.objects.all())
        context['stocks'] = len(Product.objects.all())
        context['sales'] = len(Sales.objects.all())
        context['purchases'] = len(Purchase.objects.all())
        context['category'] = len(ExpenseCategory.objects.all())
        context['expenses'] = len(Expenses.objects.all())
        context['company'] = Company.objects.all().values()

        return context

@method_decorator(decorators, name='dispatch')
class Setting(TemplateView):
    template_name = 'accounts/setting.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company'] = Company.objects.all()
        context['stocks_list'] = Product.objects.all().values()
        context['expenses_list'] = Expenses.objects.all().values()
        return context

class AccountPDFView(PDFTemplateView):
    template_name = 'accounts/account_report.html'

    def get_context_data(self, **kwargs):
        dataset = User.objects.values(
                                'username','groups','email',
                                'is_admin','is_active').order_by('id')
        context = super(AccountPDFView, self).get_context_data(
            pagesize='A4',
            title='Account Report',
            **kwargs
        )
        for data in dataset:
            data['groups'] = Role.objects.get(id=data['groups'])

        return generate_report(context, dataset, 'Accounts List')
    
def logout_view(request):
    auth.logout(request)
    return render(request, 'accounts/logout.html',{})

templates/reports/accounts.html
{% load static %}
<script>
    function search(val){
        if (val != ""){
            pageurl = href="{% url 'search_user' %}?q="+val;
            $("#view").load(pageurl);
        }else{
            $("#view").load("{% url 'accounts' %}");
        }
    }
    $(document).ready(function() {
        document.getElementById("user_logo").style.display = "none";
        var logo = document.getElementById('nav_logo')
        var logoText = document.getElementById('nav_title')
        var img = document.getElementById("user_logo").getAttribute("src")
        var title = document.getElementById("user_logo").getAttribute("alt")
        //logo.src = img;
        logoText.innerHTML = title;

        $("button").click(function() {
            $("#view").load("{% url 'accounts' %}");
        });
    });
</script>
<div class="container my-2">
    <!-- <img id="user_logo" src="/media/{{ company.logo }}" alt="{{ company.name }}"> -->
    <img id="user_logo" src="/media/{{ logo1.png }}" alt="{{ company.name }}">
    <div class="row navbar navbar-light mb-3 text-monospace">
        <h5 class="text-uppercase font-weight-lighter">User Accounts</h5>
        {% if accounts_list %}  
            <div class="form-row">
                <div class="col col-md-8">
                    <input type="text" name="search" class="form-control" placeholder="Enter search username" oninput="search(this.value)"> 
                </div>
                <div class="col col-md-2">
                    <button type="button" class="btn btn-outline-primary">Clear Filter</button>
                </div>
            </div> 
            <a class="nav-link border border-primary px-4 py-1 text-primary"
                href="{% url 'account_report' %}"
                title="Accounts Report"><i class="fa fa-file-pdf-o mr-1"></i>Export</a>    
        {% endif %}
    </div>
    {% if not accounts_list %}
        <div class="d-flex text-monospace justify-content-center">
            <p class="">No records found! <br /><br />
            <button type="button" class="btn btn-outline-primary">Clear Filter</button>
            </p>
        </div>
    {% endif %}
    <style type="text/css">
        .parent .row:hover {
            background-color: gray;
            box-shadow: 0 1rem 1.5rem rgba(0,0,0,.07)!important;
          }
    </style>
    <!-- content -->
    {% if account_list %}
        <div class="text-monospace">
            <div class="row text-muted border-bottom mb-2">
                <div class="col-3 pl-4">Username</div>
                <div class="col-3 px-0">Role</div>
                <div class="col-3 px-0">Email</div>
                <div class="col-1">Admin</div>
                <div class="col-2">Status</div>
            </div>
            {% for account in account_list %}
                <div class="parent">
                    <div class="row highlight bg-light mb-2 py-2">
                        <div class="col-3 pl-4">{{ account.username }}</div>
                        <div class="col-3 px-0">{{ account.groups.all.0.name }}</div>
                        <div class="col-3 px-0">{{ account.email }}</div>
                        <div class="col-1">
                            {% if account.is_admin %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </div>
                        <div class="col-2">
                            {% if account.is_active %}
                                Active
                            {% else %}
                                Disabled
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div id="page" class="pagination justify-content-end mt-4"> 
                <span class="step-links">
                    <span>
                        {% if page_obj.has_previous %}
                            <a class="btn" href="#{% url 'accounts' %}?page={{ page_obj.previous_page_number }}">PREVIOUS</a>
                        {% else %}
                            <a href="#" class="btn disabled text-muted">PREVIOUS</a>
                        {% endif %}
                    </span>
                    <span>
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}
                    </span>
                    <span>
                        {% if page_obj.has_next %}
                            <a class="btn" href="#{% url 'accounts' %}?page={{ page_obj.next_page_number }}">NEXT</a>
                        {% else %}
                            <a href="#" class="btn disabled text-muted">NEXT</a>
                        {% endif %}
                    </span>
                </span>
            </div>
        </div>
    {% endif %}
    <!-- End of content -->
</div>

templates/reports/analysis.html
{% load static %}

<script>
    $(document).ready(function () {
        var $roles_url = $('#index .roles0').attr('data-url');
        var $stocks_url = $('#index .stocks1').attr('data-url');
        var $sales_url = $('#index .sales0').attr('data-url');
        var $expenses_url = $('#index .expenses0').attr('data-url');
        $.ajax({
            url: $roles_url,
            dataType: 'json',
            success: function (data) {
                if(data.series[0].data.length > 0){
                    Highcharts.chart("roles0", data);
                    $('#index .highcharts-credits').remove()
                }
            }
        });
        $.ajax({
            url: $stocks_url,
            dataType: 'json',
            success: function (data) {
                if(data.series[0].data.length > 0){
                    Highcharts.chart("stocks1", data);
                    $('#index .highcharts-credits').remove()
                }
            }
        });
        $.ajax({
            url: $sales_url,
            dataType: 'json',
            success: function (data) {
                if(data.series[0].data.length > 0){
                    Highcharts.chart("sales0", data);
                    data.chart.type = 'column'
                    Highcharts.chart("sales1", data);
                    $('#index .highcharts-credits').remove()
                }
            }
        });
        $.ajax({
            url: $expenses_url,
            dataType: 'json',
            success: function (data) {
                if(data.series[0].data.length > 0){
                    Highcharts.chart("expenses0", data);
                    data.chart.type = 'column'
                    Highcharts.chart("expenses1", data);
                    $('#index .highcharts-credits').remove()
                }
            }
        });
    });
</script>
<div class="container my-4" style="max-width: 90%;">
    <h5 class="text-uppercase font-weight-lighter text-primary ml-3">Analytics</h5>
    <div class="row justify-content-center">
        <div id="roles0" class="roles0 mt-5 col-5 shadow" name="roles0" data-url="{% url 'roles_data' %}"></div>
        <div id="stocks1" class="stocks1 ml-5 mt-5 col-5 shadow" name="stocks1" data-url="{% url 'stocks_data' %}"></div>
    </div>
</div>
<div class="container my-5" style="max-width: 90%;">
    <div class="row my-5 justify-content-center">
        <div id="sales0" class="sales0 mt-5 col-5 shadow" name="sales0" data-url="{% url 'sales_data' %}"></div>
        <div id="sales1" class="sales1 ml-5 mt-5 col-5 shadow" name="sales1"></div>
    </div>
</div>
<div class="container my-5" style="max-width: 90%;">
    <div class="row my-5 justify-content-center">
        <div id="expenses0" class="expenses0 mt-5 col-5 shadow" name="expenses0" data-url="{% url 'expenses_data' %}"></div>
        <div id="expenses1" class="expenses1 ml-5 mt-5 col-5 shadow" name="expenses1"></div>
    </div>
</div>

templates/reports/roles.html
{% load static %}

<div class="container my-2">
    <div class="row navbar navbar-light mb-3 text-monospace ">
        <h5 class="text-uppercase font-weight-lighter">Account Roles</h5>
    </div>
    <style type="text/css">
        .parent .row:hover {
            background-color: gray;
            box-shadow: 0 1rem 1.5rem rgba(0,0,0,.07)!important;
          }
    </style>
    <!-- content -->
    <div class="text-monospace">
        <div class="row text-muted border-bottom mb-2">
            <div class="col-3 pl-5">Role</div>
            <div class="col-5 px-0">Description</div>
            <div class="col-4 px-0">Total Users</div>
        </div>
        {% for role in roles %}
            <div class="parent">
                <div class="row highlight bg-light mb-2 py-2">
                    <div class="col-3 pl-5">{{ role.name }}</div>
                    <div class="col-5 px-0">{{ role.description }}</div>
                    <div class="col-4 px-0">{{ role.user_set.count }}</div>
                </div>
            </div>
        {% endfor %}
        <div id="page" class="pagination justify-content-end mt-4"> 
            <span class="step-links">
                <span>
                    {% if page_obj.has_previous %}
                        <a class="btn" href="#{% url 'roles' %}?page={{ page_obj.previous_page_number }}">PREVIOUS</a>
                    {% else %}
                        <a href="#" class="btn disabled text-muted">PREVIOUS</a>
                    {% endif %}
                </span>
                <span>
                    Page {{ page_obj.number }} of {{ paginator.num_pages }}
                </span>
                <span>
                    {% if page_obj.has_next %}
                        <a class="btn" href="#{% url 'roles' %}?page={{ page_obj.next_page_number }}">NEXT</a>
                    {% else %}
                        <a href="#" class="btn disabled text-muted">NEXT</a>
                    {% endif %}
                </span>
            </span>
        </div>
    </div>
    <!-- End of content -->
</div>

templates/reports/sales.html
{% load static %}
<script>
    function search(val){
        if (val != ""){
            pageurl = href="{% url 'search_sale' %}?q="+val;
            $("#view").load(pageurl);
        }else{
            $("#view").load("{% url 'sales_list' %}");
        }
    }
    $(document).ready(function() {
        $("button").click(function() {
            $("#view").load("{% url 'sales_list' %}");
        });
    });
</script>
<div class="container my-2">
    <div class="row navbar navbar-light mb-3 text-monospace ">
        <h5 class="text-uppercase font-weight-lighter">Sales List</h5>
        {% if sales_list %}  
            <div class="form-row">
                <div class="col col-md-8">
                    <input type="text" name="search" class="form-control" placeholder="Enter search name" oninput="search(this.value)"> 
                </div>
                <div class="col col-md-2">
                    <button type="button" class="btn btn-outline-primary">Clear Filter</button>
                </div>
            </div> 
            <a class="nav-link border border-primary px-4 py-1 text-primary"
                href="{% url 'sales_report' %}"
                title="Sales Report"><i class="fa fa-file-pdf-o mr-1"></i>Export</a>    
        {% endif %}
    </div>
    {% if not sales_list %}
        <div class="d-flex text-monospace justify-content-center">
            <p class="">No records found! <br /><br />
            <button type="button" class="btn btn-outline-primary">Clear Filter</button>
            </p>
        </div>
    {% endif %}
    <style type="text/css">
        .parent .row:hover {
            background-color: gray;
            box-shadow: 0 1rem 1.5rem rgba(0,0,0,.07)!important;
          }
    </style>
    <!-- content -->
    <div class="text-monospace">
        {% if sales_list %}
            <div class="row text-muted border-bottom mb-2">
                <div class="col-3 pl-3">Name</div>
                <div class="col-1 pl-0">Quantity</div>
                <div class="col-1 pl-0">Unit Price</div>
                <div class="col-2 pl-3">Total Amount</div>
                <div class="col-2 pl-3">Seller</div>
                <div class="col-3 pl-3">Date of Sell</div>
            </div>
            {% for sale in sales_list %}
                <div class="parent">
                    <div class="row highlight bg-light mb-2 py-2">
                        <div class="col-3 pl-3">{{ sale.name }}</div>
                        <div class="col-1 pl-0">{{ sale.quantity }}</div>
                        <div class="col-1 pl-0">{{ sale.unit_price }}</div>
                        <div class="col-2 pl-3">{{ sale.total_amount }}</div>
                        <div class="col-2 pl-3">{{ sale.sold_by }}</div>
                        <div class="col-3 pl-3">{{ sale.sold_at }}</div>
                    </div>
                </div>
            {% endfor %}
            <div id="page" class="pagination justify-content-end mt-4"> 
                <span class="step-links">
                    <span>
                        {% if page_obj.has_previous %}
                            <a class="btn" href="#{% url 'sales' %}?page={{ page_obj.previous_page_number }}">PREVIOUS</a>
                        {% else %}
                            <a href="#" class="btn disabled text-muted">PREVIOUS</a>
                        {% endif %}
                    </span>
                    <span>
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}
                    </span>
                    <span>
                        {% if page_obj.has_next %}
                            <a class="btn" href="#{% url 'sales' %}?page={{ page_obj.next_page_number }}">NEXT</a>
                        {% else %}
                            <a href="#" class="btn disabled text-muted">NEXT</a>
                        {% endif %}
                    </span>
                </span>
            </div>
        {% endif %}
    </div>
    <!-- End of content -->
</div>